development:
  adapter: postgresql
  database: sloth_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: sloth_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sloth_prod
  pool: 5
  timeout: 5000